In [1]:
#!/usr/bin/env python

This code test the Nystrom method<br>
Given a symmetrick kernel matrix $K \in \mathbb{R}^{n \times n}$ and a submatrix L<br>
$$K = \begin{bmatrix} A & B^T \\ B & C \end{bmatrix}, \quad L = \begin{bmatrix} A \\ B \end{bmatrix}$$<br>
We define the eigenvalues of matrix $A \in \mathbb{R}^{q \times q}$ (where $q << n$) as <br>
$$\sigma(A) = \{\sigma_1, \sigma_2, ..., \sigma_q\}$$<br>
We define the eigenvectors of matrix $A$ as <br>
$$V(A) = \{v_1, v_2, ..., v_q\}$$

The Nystrom method allows us to compute <br>
1. The Entire $K$ matrix using $L$<br>
2. The eigenvectors of $K$ using the eigenvectors of $A$<br>
3. The inverse of $K$

The Nystrom method explained<br>
1. We randomly sample q samples and use that to form the top left matrix A<br>
2. We find $\sigma(A)$ and $V(A)$ <br>
3. We use the r most dominant eigenvectors of A to approximate the eigenfunctions $\phi$<br>
	If we define the feature map <br>
	$$\Psi_q = \begin{bmatrix} \psi(x_1)^T \\ \psi(x_2)^T \\ .. \\ \psi(x_q)^T \end{bmatrix}$$<br>
	Then the relationship between the eigenfunction $\phi_i$ and the eigenvector $v_i$ is<br>
	$$\phi_i = \frac{1}{\sqrt{\sigma_i}} \Psi_q^T v_i$$<br>
4. Once we approximated the eigenfunction, we can use it to approximate $K$ via the following derivation<br>
$$K = \Phi \Phi^T$$<br>
$$K = \begin{bmatrix}  \phi_1(x_1) & \phi_2(x_1) & .. & \phi_r(x_1)\\  \phi_1(x_2) & \phi_2(x_2) & .. & \phi_r(x_2)\\ ... & ... & ... & ...\\ \phi_1(x_n) & \phi_2(x_n) & .. & \phi_r(x_n) \end{bmatrix} \begin{bmatrix}  \phi_1(x_1) & \phi_2(x_1) & .. & \phi_r(x_1)\\  \phi_1(x_2) & \phi_2(x_2) & .. & \phi_r(x_2)\\ ... & ... & ... & ...\\ \phi_1(x_n) & \phi_2(x_n) & .. & \phi_r(x_n) \end{bmatrix}^T $$<br>
$$K = \begin{bmatrix} \frac{1}{\sqrt{\sigma_1}} \Psi_n \Psi_q^T v_1  & \frac{2}{\sqrt{\sigma_2}} \Psi_n \Psi_q^T v_2 & ... & \frac{1}{\sqrt{\sigma_r}} \Psi_n \Psi_q^T v_r\end{bmatrix} \begin{bmatrix}  \phi_1(x_1) & \phi_2(x_1) & .. & \phi_r(x_1)\\  \phi_1(x_2) & \phi_2(x_2) & .. & \phi_r(x_2)\\ ... & ... & ... & ...\\ \phi_1(x_n) & \phi_2(x_n) & .. & \phi_r(x_n) \end{bmatrix}^T $$<br>
$$K =  (\Psi_n \Psi_q^T V \Sigma) (\Psi_n \Psi_q^T V \Sigma)^T$$<br>
where<br>
$$\Sigma = \begin{bmatrix} \frac{1}{\sqrt{\sigma_1}} & 0 & 0 & ... \\ 0 &  \frac{1}{\sqrt{\sigma_2}} & 0 & ... \\ 0 &  0 & \frac{1}{\sqrt{\sigma_2}} & ... \\ ... &  ... & ... & ... \end{bmatrix} $$<br>
Therefore we have<br>
$$K =  (LV\Sigma) (\Sigma V^TL^T)$$<br>
$$K =  \Phi \Phi^T$$

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn 
from sklearn.utils import shuffle
from sklearn.kernel_approximation import Nystroem
from tools import *

Initialize all the setting

In [3]:
X = csv_load('../dataset/wine.csv', shuffle_samples=True)
q = 30				# size of submatrix A
n = X.shape[0]		# number of total samples
γ = get_rbf_γ(X)	# γ used for the gaussian kerenl

Use Nystrom to approximate the kernel

In [4]:
Xa = X[0:q, :]	# A will come from Xa
L = sklearn.metrics.pairwise.rbf_kernel(X, Y=Xa, gamma=γ)
A = L[0:q,:]
[σs,V] = np.linalg.eig(A)
V = V[:,0:10] # only keeping the largest eigenvectors
Σ = np.diag(1/(np.sqrt(σs[0:10])))
Φ = L.dot(V).dot(Σ)
ǩ = Φ.dot(Φ.T)

Use SKlearn to approximate the kernel

In [5]:
feature_map_nystroem = Nystroem(gamma=γ, random_state=1, n_components=q)
Φ2 = feature_map_nystroem.fit_transform(X)
K2 = Φ2.dot(Φ2.T)

Compute the actual kernel

In [6]:
K = sklearn.metrics.pairwise.rbf_kernel(X, gamma=γ)

Display the results<br>
Notice that even though we only used 30 samples to approximate the entire 178 sample, <br>
we still got really good approximation

In [7]:
a= 100; b= 107
print_two_matrices_side_by_side(K[a:b, a:b], ǩ[a:b, a:b], title1='Actual Kernel', title2='Nystrom Kernel')
print_two_matrices_side_by_side(K[a:b, a:b], ǩ[a:b, a:b], title1='Actual Kernel', title2='Sklearn Nystrom Kernel')

                  Actual Kernel                   	Nystrom Kernel                  
[1.     0.2303 0.0173 0.5854 0.458  0.0432 0.9369]	[0.9996 0.2303 0.0172 0.5853 0.4582 0.0432 0.9368]
[0.2303 1.     0.5249 0.0229 0.8947 0.7298 0.1174]	[0.2303 0.9998 0.5248 0.0229 0.8949 0.7299 0.1175]
[0.0173 0.5249 1.     0.0005 0.2765 0.9427 0.0059]	[0.0172 0.5248 0.9997 0.0005 0.2765 0.9429 0.0058]
[0.5854 0.0229 0.0005 1.     0.0737 0.0019 0.7931]	[0.5853 0.0229 0.0005 0.9997 0.074  0.0019 0.7934]
[0.458  0.8947 0.2765 0.0737 1.     0.4505 0.2744]	[0.4582 0.8949 0.2765 0.074  0.9979 0.4503 0.2736]
[0.0432 0.7298 0.9427 0.0019 0.4505 1.     0.0166]	[0.0432 0.7299 0.9429 0.0019 0.4503 0.9998 0.0166]
[0.9369 0.1174 0.0059 0.7931 0.2744 0.0166 1.    ]	[0.9368 0.1175 0.0058 0.7934 0.2736 0.0166 0.9994]
                                                  	


                  Actual Kernel                   	Sklearn Nystrom Kernel              
[1.     0.2303 0.0173 0.5854 0.458  0.0432 0.9369]	[0.9996 0

In [8]:
avg_error = np.sum(np.absolute(K - ǩ))/(n*n)
avg_error2 = np.sum(np.absolute(K - K2))/(n*n)

In [9]:
jupyter_print('The average absolute error with Nystrom of each element is %f'% avg_error)
jupyter_print('The average absolute error with Sklearn Nystrom of each element is %f\n\n'% avg_error2)

**How to use Nystrom to approximate eigenvectors of a large matrix** <br>
The key insight is that given an approximation of the eigenfunction $\phi_i$, the corresponding eigenvector $u_i$ of the kernel matrix K is <br>
$$u_i = \frac{1}{\sqrt{\sigma_i}} \Psi_n \phi_i$$

**Method**<br>
1. use the eigenvectors $V$ of matrix A to approximate the eigenfunction<br>
where $V = [v_1, v_2, ..., v_q]$, we get an expression for the eigenfunction<br>
$$\phi_i = \frac{1}{\sqrt{\sigma_i}} \Psi_q^T v_i$$

2. Next, we plug the eigenvector into the previous equation to get the eigenvector<br>
$$u_i = \frac{1}{\sqrt{\sigma_i}} \Psi_n (\frac{1}{\sqrt{\sigma_i}} \Psi_q^T v_i)$$<br>
$$u_i = \frac{1}{\sigma_i} \Psi_n \Psi_q^T v_i$$<br>
$$u_i = \frac{1}{\sigma_i} L v_i$$<br>
$$U = L V \begin{bmatrix} \frac{1}{\sigma_1} & 0 & 0 & ... \\ 0 & \frac{1}{\sigma_2} & 0 & ... \\  0 & 0 & \frac{1}{\sigma_3} & 0 & ... \\   \end{bmatrix}$$<br>
$\Sigma$ is a diagonal matrix<br>
$$\bar{U} = L V \Sigma$$

In [10]:
jupyter_print("We now approximate the eigenvector with only 30 samples")
Σ = np.diag(1/σs[0:10]) 	# notice that Σ here is defined slightly differently
Ū = L.dot(V).dot(Σ)			# approximate eigenvector of the larger matrix
[Λ, U] = np.linalg.eig(K)	# compute the "actual" eigenvectors

In [11]:
jupyter_print("Notice that the approximation is not that great unless you are using a large amount of samples. ")
jupyter_print("For this reason, it makes sense to combine random svd with nystrom to approximate the eigenvectors")
print_two_matrices_side_by_side(U[0:10, 0:3], Ū[0:10, 0:3], title1='Actual eigenvectors', title2='Approximated Eigenvectors')

   Actual eigenvectors   	Approximated Eigenvectors
[-0.0424 -0.1298 -0.026 ]	[-0.0646  0.3456  0.0331]
[-0.0879  0.0552 -0.0449]	[-0.2286 -0.0594 -0.0606]
[-0.081   0.0644 -0.0766]	[-0.2193 -0.084  -0.1542]
[-0.0348 -0.1319 -0.064 ]	[-0.0499  0.3633 -0.0501]
[-0.0752  0.0672 -0.0929]	[-0.2086 -0.0948 -0.2056]
[-0.0862  0.0578 -0.0531]	[-0.2264 -0.066  -0.0845]
[-0.0178 -0.1113 -0.139 ]	[-0.0226  0.3481 -0.2229]
[-0.0912  0.0465 -0.0219]	[-0.2313 -0.0389  0.0053]
[-0.0904  0.049  -0.0281]	[-0.231  -0.0446 -0.012 ]
[-0.0879  0.0555 -0.0457]	[-0.2291 -0.06   -0.0621]
                         	




In [12]:
jupyter_print("Let's perform the nystrom eigenvector approximation, but with a lot more samples, q=150, instead of just 30 samples")
#	Initialize all the setting
q = 150				# size of submatrix A

Use Nystrom to approximate the kernel

In [13]:
Xa = X[0:q, :]	# A will come from Xa
L = sklearn.metrics.pairwise.rbf_kernel(X, Y=Xa, gamma=γ)
A = L[0:q,:]
[σs,V] = np.linalg.eig(A)
V = V[:,0:10] # only keeping the largest eigenvectors

In [14]:
Σ = np.diag(1/σs[0:10]) 	# notice that Σ here is defined slightly differently
Ū = L.dot(V).dot(Σ)			# approximate eigenvector of the larger matrix

In [15]:
jupyter_print("Notice how much more accurate the approximation becomes!!!")
print_two_matrices_side_by_side(U[0:10, 0:3], Ū[0:10, 0:3], title1='Actual eigenvectors', title2='Approximated Eigenvectors')

   Actual eigenvectors   	Approximated Eigenvectors
[-0.0424 -0.1298 -0.026 ]	[ 0.0476 -0.1382  0.0108]
[-0.0879  0.0552 -0.0449]	[ 0.0977  0.0573  0.0482]
[-0.081   0.0644 -0.0766]	[ 0.0904  0.0661  0.0825]
[-0.0348 -0.1319 -0.064 ]	[ 0.0395 -0.1422  0.0521]
[-0.0752  0.0672 -0.0929]	[ 0.0842  0.0687  0.1   ]
[-0.0862  0.0578 -0.0531]	[ 0.0959  0.0598  0.057 ]
[-0.0178 -0.1113 -0.139 ]	[ 0.0211 -0.1242  0.1387]
[-0.0912  0.0465 -0.0219]	[ 0.1012  0.0488  0.0232]
[-0.0904  0.049  -0.0281]	[ 0.1003  0.0513  0.0301]
[-0.0879  0.0555 -0.0457]	[ 0.0977  0.0576  0.0491]
                         	


