In [1]:
#!/usr/bin/env python

In [2]:
import numpy as np
from numpy import array

In [3]:
X = array([	[2,1],
			[3,2],
			[1,0],
			[8,3]])

default a is not in column format

In [4]:
for xᵢ in X: print(xᵢ)	

[2 1]
[3 2]
[1 0]
[8 3]


ensure column format by reshaping

In [5]:
for xᵢ in X: print(xᵢ.reshape((2,1)))	

[[2]
 [1]]
[[3]
 [2]]
[[1]
 [0]]
[[8]
 [3]]


If you want to perform<br>
$$\sum_{i=1}^4 x_i = x_1 + x_2 + x_3 + x_4$$

In [6]:
y = np.array([[0],[0]])
for xᵢ in X: y = y + xᵢ.reshape((2,1)) 
print(y)

[[14]
 [ 6]]


Or you can just do

In [7]:
print(np.sum(X, axis=0))

[14  6]
