In [1]:
#!/usr/bin/env python

In [2]:
from sklearn.metrics.pairwise import rbf_kernel
import numpy as np
from numpy import exp as e
from numpy import zeros, array, reshape

Write my own kernel

In [3]:
X = array([[1,2],[0,1],[1,0]])

In [4]:
def k(xi, xj):
	γ = 1
	d = (xi - xj).T.dot((xi - xj))
	return e(-γ*d)

In [5]:
K = zeros((3,3))
for i, xi in enumerate(X):
	for j, xj in enumerate(X):
		xi = reshape(xi, (2,1))
		xj = reshape(xj, (2,1))
		K[i,j] = k(xi, xj)

In [6]:
print(K)

[[1.         0.13533528 0.01831564]
 [0.13533528 1.         0.13533528]
 [0.01831564 0.13533528 1.        ]]


Use sklearn to generate the kernel<br>
Notice it is the same as calculated by the equation

In [7]:
K = rbf_kernel(X, gamma=1)
print(K)

[[1.         0.13533528 0.01831564]
 [0.13533528 1.         0.13533528]
 [0.01831564 0.13533528 1.        ]]
