In [16]:
import autograd.numpy as np
from autograd import grad

In [17]:
def relu(w, x): 
	v = np.dot(np.transpose(w),x)
	return np.maximum(0, v)

def grad_relu(w,x):
	if w.T.dot(x) > 0:
		return x
	else:
		return 0
for i in range(3):
	#	Initial setup
	x = np.random.randn(2,1)
	w = np.random.randn(2,1)
	
	grad_foo = grad(relu)       # Obtain its gradient function
	print('w.dot(x) = %.3f'%x.T.dot(w))
	print('Autogen Gradient : \n', grad_foo(w,x), '\n')
	print('Theoretical Gradient : \n', grad_relu(w,x), '\n\n')

w.dot(x) = 1.201
Autogen Gradient : 
 [[-0.53292822]
 [ 0.70579309]] 

Theoretical Gradient : 
 [[-0.53292822]
 [ 0.70579309]] 


w.dot(x) = -0.021
Autogen Gradient : 
 [[0.]
 [0.]] 

Theoretical Gradient : 
 0 


w.dot(x) = -0.139
Autogen Gradient : 
 [[0.]
 [0.]] 

Theoretical Gradient : 
 0 


