In [1]:
#!/usr/bin/env python

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
import numpy as np

1st (preferred) approach to center and scale data.

In [3]:
X = np.array([[3, 0, 400], [2, 1, 200], [2, 2, 500], [1, 1, 100]])

Initialize the StandardScaler

In [4]:
scaler = StandardScaler()

Fit the scaler to the data and transform the data

In [5]:
scaled_data = scaler.fit_transform(X)

In [6]:
print("Original Data:\n", X)
print("Centered and Scaled Data:\n", scaled_data)

Original Data:
 [[  3   0 400]
 [  2   1 200]
 [  2   2 500]
 [  1   1 100]]
Centered and Scaled Data:
 [[ 1.41421356 -1.41421356  0.63245553]
 [ 0.          0.         -0.63245553]
 [ 0.          1.41421356  1.26491106]
 [-1.41421356  0.         -1.26491106]]


2nd approach to center and scale data.<br>
----------------------------<br>
Original data

In [7]:
X = np.array([[3, 0, 400], [2, 1, 200], [2, 2, 500], [1, 1, 100]])
print("Original Data:\n", X)

Original Data:
 [[  3   0 400]
 [  2   1 200]
 [  2   2 500]
 [  1   1 100]]


Scale the data

In [8]:
X_scaled = preprocessing.scale(X)
print("\nScaled Data:\n", X_scaled)


Scaled Data:
 [[ 1.41421356 -1.41421356  0.63245553]
 [ 0.          0.         -0.63245553]
 [ 0.          1.41421356  1.26491106]
 [-1.41421356  0.         -1.26491106]]


Verify the mean and standard deviation of the scaled data

In [9]:
print("\nMean of Scaled Data (should be close to 0):\n", np.mean(X_scaled, axis=0))
print("\nStandard Deviation of Scaled Data (should be close to 1):\n", np.std(X_scaled, axis=0))


Mean of Scaled Data (should be close to 0):
 [0. 0. 0.]

Standard Deviation of Scaled Data (should be close to 1):
 [1. 1. 1.]
